import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
dimensions = { columns = 120, lines = 29 }

padding.x = 10
padding.y = 10

option_as_alt = "Both"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }

size = 16
